---

name: NGINX Container Build

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

    # Install Packer
      - name: Install Packer
        run: |
          sudo apt-get update 
          sudo apt-get install -y curl unzip
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Build Packer
        env: 
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            PUSH_REPO:          ${{ secrets.PUSH_REPO }}
        shell: bash
        run: |
          cd containers
          packer build --var "dockerhub_username=$DOCKERHUB_USERNAME" --var "dockerhub_password=$DOCKERHUB_PASSWORD" --var "push_repo=$PUSH_REPO" ./nginx.pkr.hcl 
